/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri May 25 13:59:15 2018. */

#include "test.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t _test_struct_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, _test_struct, ts1, ts1, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, _test_struct, ts2, ts1, 0),
    PB_LAST_FIELD
};

const pb_field_t test_message_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, test_message, value1, value1, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, test_message, value2, value1, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, test_message, the_stru, value2, &_test_struct_fields),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
